
# ?????http??????????https??
custom:
  request-type: http # ?????http
  http-port: 8080


server:
  port: 9980 # ??
  # ??SSL
  ssl:
    #enabled: true # ???true
    key-store: classpath:ssl/xxx.jks # SSL????????????????
    key-store-type: JKS # ????
    key-store-password: ?????? # ????,???key-store-password???key-password