server:
  port: 8899


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1 # 使用的数据库
    timeout: 30000 # 单位： 毫秒
    connect-timeout: 60000
    lettuce: # 一共有两种redis客户端： lettuce、jedis
      pool:
        max-active: 8 # 最大连接数
        min-idle: 0 # 最小空闲
        max-idle: 8 # 最大空闲
        max-wait: -1 # 最大阻塞等待时间(负数表示没限制)
